### ISSUE TITLE
[Question] Migration on Qt? 

### ISSUE THREAD

**Issue by ma3yta** [budgie-desktop/budgie-rd#15]
Hello. 
Do you still have plans for migration on Qt? 
Is project https://github.com/solus-project/budgie-rd ``deprecated``?
...[``and all previous decisions will now be re-evaluated (Qt? Wayland? gtk4? etc)``](https://github.com/solus-project/budgie-desktop/commit/260a26f36620fbeb76e7c963f4fef154482e6993#diff-04c6e90faac2675aa89e2176d2eec7d8R31)

**Comment by ma3yta** [comment]
@JoshStrobl @ikeydoherty Any progress on migration or ETA? Or is it ``deprecated``.
https://github.com/solus-project/budgie-desktop/milestone/3
https://github.com/solus-project/budgie-desktop/issues/1568

**Comment by ckrzen** [comment]
Ack! I was curious about this too.
