### ISSUE TITLE
Replace use of QSettings

### ISSUE THREAD

**Issue by ikeydoherty** [budgie-desktop/budgie-rd#2]
Turns out QSettings is woefully limited and cannot really read a `.desktop` file properly, i.e. `;` separated values will only field the first value, with Qt believing everything following is now a comment.

Thus, roll a custom reader ..

**Comment by STiAT** [comment]
Still intend to use QSettings (by using QSettings::registerFormat / http://doc.qt.io/qt-5/qsettings.html#registerFormat) or going with a class on your own handling desktkop files?

**Comment by ikeydoherty** [comment]
Eh gonna roll our own just using a line/string parser - probably simplest given the scope

**Comment by ikeydoherty** [comment]
This is now implemented in master, just needs a bit of a cleanup
