### ISSUE TITLE
wm Use kwin？

### ISSUE THREAD

**Issue by laizhiwei123** [budgie-desktop/budgie-rd#5]
wm Use kwin？ kde fusion?

**Comment by fagoatse** [comment]
kwin - yes
kde fusion - ?? ???

**Comment by laizhiwei123** [comment]
Native KDE programs can be used?

**Comment by ikeydoherty** [comment]
IDK what a KDE Fusion is. We're currently _investigating_ KWin as an option for Budgie 11.
